version: 2
jobs:
  build-publish-trigger:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            set -e
            ./pipe_build_up_test.sh
      - run:
          name: Tag docker image
          command: |
            set -e
            declare -r NAME="${CIRCLE_PROJECT_REPONAME}"
            declare -r SHA="${CIRCLE_SHA1}"
            docker tag cyberdojo/${NAME}:latest cyberdojo/${NAME}:${SHA:0:7}
      - run:
          name: Publish tagged docker image on dockerhub
          command: |
            set -e
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            declare -r NAME="${CIRCLE_PROJECT_REPONAME}"
            declare -r SHA="${CIRCLE_SHA1}"
            docker push cyberdojo/${NAME}:${SHA:0:7}
            docker push cyberdojo/${NAME}:latest
            docker logout
      - run:
          name: Trigger dependent repos
          command: |
            set -e
            TRIGGER=trigger-dependent-repos.sh
            curl -O --fail ${CIRCLECI_SCRIPT_DIR}/${TRIGGER}
            chmod 700 ./${TRIGGER}
            # ./${TRIGGER} inserter runner # todo

workflows:
  version: 2
  build-publish-trigger:
    jobs:
      - build-publish-trigger:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
